# NOTE: The env groups should be first created in the Render dashboard
# Since they do not allow `sync: false` in env groups, this is seems to be the only way

projects:
  - name: test-bff-project
    environments:
      - name: smoke
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              # url: ghcr.io/mmartiaga/apollo-bff-test/gateway:latest
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: content-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              # url: ghcr.io/mmartiaga/apollo-bff-test/content:latest
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: products-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              # url: ghcr.io/mmartiaga/apollo-bff-test/products:latest
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-smoke-env-group

